# Generated by Django 4.1.3 on 2022-11-07 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LootboxTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('included_tiers', multiselectfield.db.fields.MultiSelectField(choices=[('TIER_1', 'Legendary'), ('TIER_2', 'Epic'), ('TIER_3', 'Rare'), ('TIER_4', 'Uncommon'), ('TIER_5', 'Common')], max_length=100)),
                ('coins_price', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('spacebucks', models.FloatField(default=10.0)),
                ('coins', models.BigIntegerField(default=1000)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_token', models.CharField(editable=False, max_length=100, unique=True)),
                ('datetime_sent', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0.0)),
                ('is_accepted', models.BooleanField(default=False)),
                ('datetime_accepted', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='api.player')),
                ('sender', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='NFTCollectible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', editable=False, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('tier', models.CharField(choices=[('TIER_1', 'Legendary'), ('TIER_2', 'Epic'), ('TIER_3', 'Rare'), ('TIER_4', 'Uncommon'), ('TIER_5', 'Common')], default='TIER_5', max_length=10)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.player')),
            ],
        ),
    ]
