# Generated by Django 4.1.3 on 2022-11-07 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='nft_token',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='nft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nftcollectible'),
        ),
    ]
