# Generated by Django 4.1.3 on 2022-11-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_purchase_alter_nftcollectible_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftcollectible',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
