# Generated by Django 4.1.3 on 2022-11-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_purchaserequest_delete_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='datetime',
            new_name='datetime_sent',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='datetime_accepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
