# Generated by Django 4.1.3 on 2022-11-07 13:48

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_nftcollectible_price_nftcollectible_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='LootboxTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_tiers', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Legendary'), ('2', 'Epic'), ('3', 'Rare'), ('4', 'Uncommon'), ('5', 'Common')], max_length=100)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='nftcollectible',
            name='tier',
            field=models.CharField(choices=[('1', 'Legendary'), ('2', 'Epic'), ('3', 'Rare'), ('4', 'Uncommon'), ('5', 'Common')], default='5', max_length=10),
        ),
    ]
