# Generated by Django 4.1.3 on 2022-11-07 13:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_lootboxtier_alter_nftcollectible_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lootboxtier',
            name='included_tiers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('TIER_1', 'Legendary'), ('TIER_2', 'Epic'), ('TIER_3', 'Rare'), ('TIER_4', 'Uncommon'), ('TIER_5', 'Common')], max_length=100),
        ),
        migrations.AlterField(
            model_name='nftcollectible',
            name='tier',
            field=models.CharField(choices=[('TIER_1', 'Legendary'), ('TIER_2', 'Epic'), ('TIER_3', 'Rare'), ('TIER_4', 'Uncommon'), ('TIER_5', 'Common')], default='TIER_5', max_length=10),
        ),
    ]
