# Generated by Django 4.1.3 on 2022-11-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_lootboxtier_included_tiers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nftcollectible',
            old_name='user',
            new_name='owner',
        ),
    ]
