# Generated by Django 4.1.3 on 2022-11-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_user_nftcollectible_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
