# Generated by Django 4.1.3 on 2022-11-07 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_remove_purchaserequest_nft_purchaserequest_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lootboxtier',
            name='price',
        ),
        migrations.AddField(
            model_name='lootboxtier',
            name='coins_price',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='lootboxtier',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('spacebucks', models.FloatField(default=0.0)),
                ('game_coins', models.BigIntegerField(default=0)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
