# Generated by Django 4.1.3 on 2022-11-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_lootboxtier_price_lootboxtier_coins_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftcollectible',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/images/'),
        ),
    ]
