# Generated by Django 4.1.3 on 2022-11-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_nftcollectible_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_coins',
            field=models.BigIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='player',
            name='spacebucks',
            field=models.FloatField(default=10.0),
        ),
    ]
