# Generated by Django 4.1.3 on 2022-11-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_player_game_coins_alter_player_spacebucks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='game_coins',
            new_name='coins',
        ),
    ]
