# Generated by Django 4.1.3 on 2022-11-07 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_game_coins_player_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='receiver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='api.player'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='sender',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='api.player'),
        ),
    ]
